steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Run tests (if you have any)
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['test']

  # Build your app (if you have a build step)
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Optionally, build a Docker image and push it to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/portal:$COMMIT_SHA', '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/portal:$COMMIT_SHA'
    ]

images:
  - 'gcr.io/$PROJECT_ID/portal:$COMMIT_SHA'
